import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor.style]
shape = "Beam"
blinking = "on"

[cursor]
blink_interval = 650

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
# family = "Iosevka Nerd Font"
family = "Jetbrains Mono Nerd Font"
style = "Bold"

[window]
startup_mode = "Maximized"
padding = {x = 15, y = 7}

[mouse]
hide_when_typing = true
